name: dash_chat
description: "A dash chatbot MCP client"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1
environment:
  sdk: ^3.8.0-132.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.7.7+1
  google_generative_ai: ^0.4.0
  dart_mcp: ^0.2.0
  cli_util: ^0.4.2
  async: ^2.13.0
  args: ^2.7.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dash.png
    - assets/gemini.png

dependency_overrides:
  dart_mcp:
    path: ../../
